# Generated by Django 4.0.3 on 2022-03-15 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='especies',
            old_name='Nome_Popular',
            new_name='Nome_popular',
        ),
    ]
